sudo: required

language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

before_script:
  - bash scripts/setup.sh

script:
  - bash scripts/lint.sh
  - bash scripts/build.sh
