sudo: required

cache:
  directories:
    - node_modules

services:
  - docker

before_script:
  - bash scripts/setup.sh

script:
  - bash scripts/lint.sh
  - bash scripts/build.sh

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
