title: Jekyll Starter Site
description: >
  Jekyll, typescript, webpack, docker starter site.
baseurl: ""
url: ""
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ts
  - scss
keep_files:
  - assets
